### ISSUE TITLE
Support JS libraries

### ISSUE THREAD

**Issue by dzarda** [cubicap/Jaculus-tools#2]
Minified versions of libraries (i.e. RxJS or rx.lite) can be found only in pure .js form. We should support including them in the build and flash processes. Their accompanying d.ts files should also be handled.

**Comment by cubicap** [comment]
JS libraries can be used "as-is" as long as they can be run under ES2023 and type annotations are provided (`.d.ts` files).

Source files can be placed in the `src` directory and type annotations in `@types`.
